/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.js';
import { Route as PostsRouteImport } from './routes/posts.js';
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId.js';
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport
});
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute
});
const PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute
};
const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren);
const rootRouteChildren = {
  PostsRoute: PostsRouteWithChildren
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
